name: Conventional commits

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  pr-checker:
    name: PR title
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EkoCommunications/PRChecks/pr-title@develop