name: Release

on:
  workflow_dispatch:

jobs:
  npm_publish:
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2

      - name: configure git
        run: |
          git config user.name "alfred-amity-bot"
          git config user.email "developers@amity.co"

      - name: install deps
        run: npm ci

      - name: version bump
        run: npx --yes standard-version

      - name: build package
        run: npm run build

      - name: npm publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: commit changes
        run: git push --follow-tags

      - name: debugger
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 15
