name: PR task checker
on:
  pull_request:
    types: [opened, edited]

jobs:
  task-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: EkoCommunications/PRChecks/task-list@develop
        with:
          skip_on: feature branch
